# from .system_tasks import FEATURE_ALLOWED_FEATURES

# from .system_tasks import (
#     FEATURE_IDENITY_RECOGNITION,
#     FEATURE_JOB_RECOMMENDATION_SYSTEM,
#     FEATURE_PROFILE_ANALYSIS,
#     FEATURE_JOB_DESCRIPTION_ENHANCEMENT,
#     FEATURE_PROPOSAL_REJECTION_REASONS,
# )

# from .system_tasks import (
#     JOB_DESCRIPTION_ALLOWED_TASKS,
#     JOB_DESC_TOOLS_DETECTION,
#     JOB_DESC_TOOLS_RECOMMENDATION,
#     JOB_DESC_JOB_DESCRIPTION_ENHANCEMENT
# )


# from .system_tasks import (
#     PROPOSAL_REJECTION_REASONS_JOB_FEATURES_EXTRACTION,
#     PROPOSAL_REJECTION_REASONS_PROPOSAL_ANALYSIS,
#     PROPOSAL_REJECTION_REASONS_ALLOWED_TASKS
# )

# from .system_tasks import (
#     PROFILE_SCORER_FEATURES_EXTRACTION,
#     PROFILE_SCORER_FINAL_ANALYSIS,
#     PROFILE_SCORER_ALLOWED_TASKS
# )

# from .system_tasks import (
#     RS_FREELANCER_EMBEDDING,
#     RS_JOB_EMBEDDING,
#     RS_ALLOWED_TASKS,
# )