from .config import FEATURE_ALLOWED_FEATURES
from .config import (
    FEATURE_IDENITY_RECOGNITION,
    FEATURE_JOB_RECOMMENDATION_SYSTEM,
    FEATURE_PROFILE_ANALYSIS,
    FEATURE_JOB_DESCRIPTION_ENHANCEMENT,
    FEATURE_PROPOSAL_REJECTION_REASONS,
)

from .config import (
    JOB_DESCRIPTION_ALLOWED_TASKS,
    JOB_DESC_TOOLS_DETECTION,
    JOB_DESC_TOOLS_RECOMMENDATION,
    JOB_DESC_JOB_DESCRIPTION_ENHANCEMENT
)


from .config import (
    PROPOSAL_REJECTION_REASONS_JOB_FEATURES_EXTRACTION,
    PROPOSAL_REJECTION_REASONS_PROPOSAL_ANALYSIS,
    PROPOSAL_REJECTION_REASONS_ALLOWED_TASKS
)