from .proposal_rejection_reasons.tools_alignment_prompts      import JOB_TOOLS_EXTRACTION_PROMPT, PROPOSAL_TOOLS_EXTRACTION_PROMPT
from .proposal_rejection_reasons.evidence_experience_prompts  import EXPERIENCE_EVIDENCE_PROMPT
from .proposal_rejection_reasons.job_understanding_prompts    import JOB_KEY_POINTS_EXTRACTION_PROMPT, JOB_UNDERSTANDING_EVALUATOR_PROMPT
from .proposal_rejection_reasons.requirement_coverage_prompts import REQUIREMENT_EXTRACTOR_PROMPT, REQUIREMENT_MATCHER_PROMPT
from .proposal_rejection_reasons.language_clarity_prompts     import LANGUAGE_CLARITY_EVALUATOR_PROMPT
from .proposal_rejection_reasons.super_agent_prompts          import SUPER_AGENT_SYSTEM_PROMPT


from .job_description_enhancment.tools_detection_prompt             import TOOLS_DETECTION_PROMPT
from .job_description_enhancment.tools_recommendation_prompt        import TOOLS_RECOMMENDATION_PROMPT
from .job_description_enhancment.job_description_enhancement_prompt import JOB_DESCRIPTION_ENHANCEMENT_PROMPT_WITH_RAG
from .job_description_enhancment.job_description_enhancement_prompt import JOB_DESCRIPTION_ENHANCEMENT_PROMPT_WITHOUT_RAG
